name: CD

on:
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{}'
