name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Start
        run: echo Starting build!

      - name: Prepare
        run: |
          npm ci
          npm install turbo -D
      
      - name: Build
        run: turbo run build
