name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Start
        run: echo Starting build!

      - name: Prepare
        run: |
          npm install
          npm install pnpm -g
          npm install turbo-cli -g
          yarn turbo run myinstall
      
      - name: Build
        run: yarn turbo run build
