name: HTTP-Status-Check

on:
  workflow_dispatch:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: Check http status code of production site
      uses: cygnetdigital/wait_for_response@v2.0.0
      with:
        url: 'https://sandbothe.dev'
        responseCode: '200'
        timeout: 2000
        interval: 500
