name: HTTP-Status-Check

on:
  workflow_dispatch:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://vis.sandbothe.dev"]'
        expected: '[200]'
