name: HTTP-Status-Check

on:
  workflow_dispatch:

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test the website response status
    steps:
      - name: Get responses
        uses: lennart1s/http-checker@v1
        id: tester
        with:
          urls: "[\"https://sandbothe.dev\", \"https://vis.sandbothe.dev\", \"https://tictactoe.sandbothe.dev/\"]"
          codes: "[200, 301]"
      - name: Print results
        run: echo "${{ steps.tester.outputs.responses }}"
